dataset_id_list:
  - id: "fareselmenshawii/large-license-plate-dataset"
    source: "kaggle"
  - id: "duydieunguyen/licenseplates"
    source: "kaggle"
  - id: "ronakgohil/license-plate-dataset"
    source: "kaggle"
  - id: "bomaich/vnlicenseplate"
    source: "kaggle"
  - id: "congtuu/vietnamese-license-plate-obb"
    source: "kaggle"
  - id: "haitonthat/vietnam-license-plate-bounding-box"
    source: "kaggle"
  - id: "university-of-southeastern-philippines-cnl9c/license-plate-detection-merged-projects"
    source: "roboflow"
    format: "yolov11"
    version: 3
  - id: "ev-dshfb/license-plate-w8chc"
    source: "roboflow"
    format: "yolov11"
    version: 1
  - id: "kanwal-masroor-gv4jr/yolov7-license-plate-detection"
    source: "roboflow"
    format: "yolov11"
    version: 3
  - id: "keremberke/license-plate-object-detection"
    source: "huggingface"